name: CI

on:
  push:

env:
  CI: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v3
    - uses: actions/checkout@v3
    - run: npm install
    - run: npm run lint

  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v3
    - uses: actions/checkout@v3
    - run: npm install
    - name: run coverage
      run: npx -y c8 --reporter=lcov npm test
      env:
        NODE_ENV: cov

    - name: codecov
      uses: codecov/codecov-action@v3

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}

  test:
    needs: get-lts
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        node-version: ${{ fromJson(needs.get-lts.outputs.active) }}
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      name: Node ${{ matrix.node-version }} on ${{ matrix.os }}
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm test
      env:
        NODE_ENV: test

  get-lts:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - id: get
        uses: msimerson/node-lts-versions@v1
    outputs:
      lts: ${{ steps.get.outputs.lts }}
      active: ${{ steps.get.outputs.active }}
